### ISSUE TITLE
Missing mxMatSysWindow?

### ISSUE THREAD

**Issue by Trico-Everfire** [nekonomicon/mxtk#7]
When looking at the 2006 SDK of Valve Software's Source Engine,  both mx/mxMatSysWindow.h and win32/mxMatSysWindow.cpp can be found. Valve stipped out qt/ which means qt/mxMatSysWindow.cpp is lost to time. Is anyone aware of this file? No matter how far and wide I search there is no reference anywhere to qt/mxMatSysWindow.cpp.

**Comment by nekonomicon** [comment]
Nope.
It was original mxtk by Mete Ciragan, that was downloaded with HLMV sources from http://milkshape3d.com/.

**Comment by Trico-Everfire** [comment]
HLMV doesn't come with the mxtk sources, not that I could find, maybe you can direct me to where I can find the original mxtk?

**Comment by nekonomicon** [comment]
http://www.chumba.ch/chumbalum-soft/files/hlmv125.zip

Anyway I'm not sure where qt3 version was found, may be link already dead.

**Comment by nekonomicon** [comment]
Also, I checked [mxMatSysWindow](https://github.com/Source-SDK-Archives/source-sdk-2006-ep1/blob/master/utils/mxtk/src/win32/mxmatsyswindow.cpp#L28) source code and it looks like replacement for mxGlWindow, but with GDI/Direct3D instead of OpenGL.
